data_usage:
  # Define the keys used to identify an output;
  # entity_id is required while a secondary context grouping is optional
  entity_id: patient_nbr
  context_id: encounter_id
  # Each use case must define a primary output and target
  # Output should be in the predictions table but target may be a display name of a windowed event
  primary_output: LGBM_score
  primary_target: Readmitted within 30 Days
  # Predict time indicates the column for timestamp associated with the row
  predict_time: ScoringTime
  # Features, when present, will reduce the data loaded from predictions.
  # It does NOT need to include cohorts our outputs specified elsewhere
  features:
    - admission_type_id
    - num_medications
    - num_procedures
  # This list defines available cohort options for the default selectors
  cohorts:
    - source: age
      display_name: Age
    - source: race
      display_name: Race
    - source: gender
      display_name: Gender
  # The event_table allows mapping of event columns to those expected by the tool
  # The table must have the entity_id column and may have context_id column if being used
  event_table:
    type: Type
    time: EventTime
    value: Value
  # Events define what types of events to merge into analyses
  # Windowing defines the range of time prior to the event where predictions are considered
  events:
    - source: TargetLabel
      display_name: Readmitted within 30 Days
      window_hr: 6
      offset_hr: 0
      usage: target
  # Minimum group size to be included in the analysis
  censor_min_count: 10
